### ISSUE TITLE
timer-file

### ISSUE THREAD

**Issue by Rugambwanoreen** [wkambale/missingpersons#18]
<div id="arrest-info">
    <h2>Arrest Information</h2>
    <p id="arrest-time">Time of Arrest: <span id="time-display">Not recorded</span></p>
</div>

<script>
    function updateArrestTime() {
        const now = new Date();
        const formattedTime = now.toLocaleString();
        document.getElementById('time-display').textContent = formattedTime;
    }

    // Call updateArrestTime on page load
    window.onload = function() {
        updateArrestTime();
    };

    // Optional: Update the time every minute
    setInterval(updateArrestTime, 60000);
</script>

<style>
    #arrest-info {
        padding: 20px;
    }
    #arrest-info h2 {
        margin-top: 0;
    }
    #arrest-time {
        font-size: 1.2em;
    }
</style>

**Comment by wkambale** [comment]
added
