### ISSUE TITLE
"image" to "images"

### ISSUE THREAD

**Issue by a-situma** [wkambale/missingpersons#2]
please switch the "image" symbol to "images" to accommodate various images of arrested individual including their surrounding 

    {
        "id": 1,
        "name": "Missing Person 1",
        "images": "img/images_of_arrest.jpg",
        "status": "Missing",
        "last_known_location": "Kamwokya",
        "security_organ": "Taken by Police",
        "holding_location": "Prison",
        "twitter": "@x_handle_1",
        "sex": "Male"

**Comment by wkambale** [comment]
One should be able to add the multiple images on the same field without changing from `image` to `images`, just add a comma to separate them: "image1.jpg, image2.png"
