### ISSUE TITLE
Karungi Hamza arrested

### ISSUE THREAD

**Issue by Rugambwanoreen** [wkambale/missingpersons#30]

**Comment by Rugambwanoreen** [comment]
Kwikiriza Nova 
Ezra Byakutangaza
Jonathan Tayebwa these have been arrested as well and are at cps

**Comment by Rugambwanoreen** [comment]
Atuheibwe Victor abducted by a drone

**Comment by Rugambwanoreen** [comment]
Esther Tabamubi has been arrested and taken to an unknown location

**Comment by wkambale** [comment]
added
