### ISSUE TITLE
Mukisa Elisha has gone missing 

### ISSUE THREAD

**Issue by Ramonmwes** [wkambale/missingpersons#4]
At around 8pm in the Evening a friend of mine Mukisa Elisha while around Loy supermarket in Kisasi town just opposite the Kisasi Traffic lights 🚦, was Abducted by Security officers in plain clothes suspiciously from CI _ Crime Intelligence, and was whisked away in a tinted car to an Unknown destination, we are yet to file a missing persons statement with police 
![FB_IMG_1721584935046](https://github.com/user-attachments/assets/2e22f60d-733f-4abc-bab7-fda7ec7afb23)

**Comment by Ramonmwes** [comment]
That's not true, he was maliciously charged however the same government withdrew the same charges the next month and he was accordingly aquited confirm with the document below ⬇
![Document 57_1](https://github.com/user-attachments/assets/ac160ccf-e05e-4ebf-9f9f-816fc1e48a84)

**Comment by wkambale** [comment]
thanks for clarifying on that, @Ramonmwes.

now any new updates on Elisha?

**Comment by Ramonmwes** [comment]
No I have failed to locate he's whereabouts currently but have informed the
family
