### ISSUE TITLE
Martha Kebirungi was arrested

### ISSUE THREAD

**Issue by Rugambwanoreen** [wkambale/missingpersons#52]
location unknown

**Comment by kaybrian** [comment]
has the source been confirmed, coz twitter shows that she is still missing

**Comment by Rugambwanoreen** [comment]
yes she is still missing she was arrested no one knows whereabouts

**Comment by kaybrian** [comment]
Thank you so much

**Comment by wkambale** [comment]
Martha was updated on the list

**Comment by Rugambwanoreen** [comment]
there is that guy in a white vest tried finding his name do we have him on the list as well?
