### ISSUE TITLE
Add pagination. Missing people are getting many.

### ISSUE THREAD

**Issue by BagzieGracious** [wkambale/missingpersons#58]
It becomes cumbersome for someone to go back to the top if they are using a smaller device.

**Comment by wkambale** [comment]
if we have to do pagination, consider:

- sorting the list in newest to oldest, so that the newest entries come first.
- consider cutting into 12 per page, at 100% zoom, the site is designed to display 3 cards.

**Comment by BagzieGracious** [comment]
@wkambale don't we need to display one card per row instead of two on smaller devices? 
Seeing details on two or three cards on the same row seems hard.

![IMG_5AF26990CFB8-1](https://github.com/user-attachments/assets/ece1832b-6f00-43ae-a758-0509adc6f97c)

**Comment by iluyimbazi** [comment]
from your screenshot, the two look okay to me. I think it would become hard on 3.

**Comment by BagzieGracious** [comment]
@iluyimbazi the screenshot in this instance is stretched. But on my small phone, everything is small.
Kindly try it on your phone.

**Comment by iluyimbazi** [comment]
I am not disagreeing with you, it is totally a screen size issue here. Could you be able to tell your screen size or phone model so that they add more media queries for smaller screens? I am on 15PM and see it with no issues but clearly understand what you mean.

**Comment by BagzieGracious** [comment]
@iluyimbazi  it's 12p

**Comment by sempijja** [comment]
I earlier saw a suggestion to add pagination, though it could improve a couple of things this is a "wall" and should be treated as such without pages I think

**Comment by sempijja** [comment]
I earlier saw a suggestion to add pagination, though it could improve a couple of things this is a "wall" and should be treated as such without pages i think a scroll to top button could solve the issue of scrolling too deep.
