### ISSUE TITLE
Make sure the Analytics page doesn't open in the new tab

### ISSUE THREAD

**Issue by kaybrian** [wkambale/missingpersons#59]
- When a user clicks on the Analytics link, It is opening in a new tab. However, it would make sense if the target of the like was left blank so that it doesn't open in a new tab on the browser.

**Comment by wkambale** [comment]
also consider resizing the charts, they seem to be big and overfilling the screen.

**Comment by skapeyi** [comment]
Fixed in #65

**Comment by skapeyi** [comment]
#65 merged this should be closed now

**Comment by kaybrian** [comment]
sure am closing it now
