### ISSUE TITLE
Add funtionality to allow Non-technical people to add more people or request updates without writing code

### ISSUE THREAD

**Issue by kaybrian** [wkambale/missingpersons#60]
We need to be able to add a form on the platform that allows users to send in new data and missing people without the need to write code. This allows us to be able to crowdsource more data and real-time data for missing people.

**Comment by Musacoli** [comment]
@Slam256 has expressed interest in picking this up

**Comment by briantical** [comment]
This is crucial to the site though I had a couple of reservations/ questions. This change might/will be an additional layer of verification to address potential issues such as:
- Duplication of entries 
- Validation of the submitted entries (almost similar to above)
- Prevent malicious actors from spamming the platform with incorrect information.

Additionally, we need to define the specific data required for submission, including mandatory fields and optional data points.

Finally, we should evaluate the implications of this functionality on our current website implementation. What adjustments or enhancements will be necessary to integrate this feature seamlessly?

**Comment by kaybrian** [comment]
interesting questions raised here

**Comment by sempijja** [comment]
Someone can create a google form where to allow non technical users to submit data

**Comment by kaybrian** [comment]
How can that be connected to adding the data to the "wall", we need to automatic the process

**Comment by Slam256** [comment]
- The public can be given a form to submit data regarding missing persons. 
- we would to add authentication for approved users to be able to verify the records entered by the public.
- a dashboard or an excel sheet would be used to look through the data. 
- This process can't be fully automated (unless by AI that we need ti train) because we need. to verify the data entered by users, never trust a user.

**Comment by briantical** [comment]
@Musacoli  I think we can proceed to close this.

**Comment by Musacoli** [comment]
Shouldn't we first wait for the API implementation to be completed

**Comment by skapeyi** [comment]
This is being tested. We'll mark it as closed after we've finished testing and moving over to the new implementation.

**Comment by skapeyi** [comment]
We've a new way where authorised and authenticated users can add more people and update the data.
