### ISSUE TITLE
We have a duplicate of kirya reported. 

### ISSUE THREAD

**Issue by BagzieGracious** [wkambale/missingpersons#74]
Here are the accounts.

<img width="262" alt="Screenshot 2024-07-24 at 01 19 56" src="https://github.com/user-attachments/assets/2b11852b-67ba-4b25-80e9-e50d2a54f084">
<img width="262" alt="Screenshot 2024-07-24 at 01 19 35" src="https://github.com/user-attachments/assets/763b0005-f927-4a1d-bebc-024c4094ef49">

**Comment by kaybrian** [comment]
thank you for pointing this out

**Comment by skapeyi** [comment]
I'll raise a PR for this
