### ISSUE TITLE
Add Counters to Status Buttons

### ISSUE THREAD

**Issue by Musacoli** [wkambale/missingpersons#96]
We need to add counters to the status buttons used for filtering. The counter should represent the total number of people with that specific status

![Screenshot 2024-07-25 at 11 11 21](https://github.com/user-attachments/assets/d248df11-3bcb-4c5c-93c1-5a3b4e3f24ee)

**Comment by KimVianney** [comment]
Let me give it a go

**Comment by Musacoli** [comment]
Resolved by #102
